In [3]:
import pandas as pd

df = pd.read_csv('malaysia_aml_fraud_anomaly_transactions.csv')
df

,transaction_id,transaction_datetime,customer_id,account_id,customer_age,customer_segment,occupation,state,branch,monthly_income_myr,...,manual_red_flag_count,risk_category,anomaly_score,anomaly_or_not,fraud_label,aml_suspicious_label,sentiment_label,customer_message,investigator_note,investigation_status
0,TXN202600000,2026-01-18 19:42:00,CUST1322,ACC11122,37,Emerging Affluent,Unemployed,Kuala Lumpur,Bukit Bintang,815.28,...,1,Low,43.26,0,0,0,Neutral,Customer asked bank to verify recent activity,Local Transfer through Mobile App. Red flags c...,Not Reviewed
1,TXN202600001,2026-04-14 11:54:00,CUST1270,ACC10255,18,Mass,Self-employed,Sarawak,Kuching,8538.78,...,0,Medium,15.29,0,0,0,Positive,Customer confirmed beneficiary and transaction...,Card Purchase through Mobile App. Red flags co...,Not Reviewed
2,TXN202600002,2026-03-07 20:12:00,CUST1349,ACC10060,27,Mass,Student,Perak,Ipoh,1250.59,...,2,Low,37.80,0,0,0,Positive,Customer appreciated quick support and confirm...,Card Purchase through ATM. Red flags count: 2....,Not Reviewed
3,TXN202600003,2026-07-23 10:03:00,CUST1139,ACC10092,60,Affluent,Salaried,Melaka,Melaka Central,13357.94,...,1,Low,36.51,0,0,0,Positive,Customer confirmed beneficiary and transaction...,Wallet Top-up through International Transfer. ...,Closed - Normal
4,TXN202600004,2026-05-30 18:36:00,CUST1215,ACC10744,26,SME,Retired,Selangor,Kuching,24430.85,...,0,Medium,16.68,0,0,0,Neutral,Customer asked for account activity summary,Cash Deposit through Online Banking. Red flags...,Not Reviewed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,TXN202601495,2026-06-11 06:08:00,CUST1334,ACC10080,33,Private Banking,Salaried,Perak,Melaka Central,23431.64,...,1,Low,15.17,0,0,0,Neutral,Customer provided documents for normal verific...,Local Transfer through Card POS. Red flags cou...,Closed - False Positive
1496,TXN202601496,2026-03-01 16:58:00,CUST1109,ACC10478,42,Mass,Business Owner,Negeri Sembilan,Johor Bahru,7870.29,...,0,Medium,11.34,0,0,0,Neutral,Customer asked for account activity summary,Cash Deposit through Card POS. Red flags count...,Closed - Normal
1497,TXN202601497,2026-04-15 14:00:00,CUST1035,ACC10148,50,Mass,Salaried,Kuala Lumpur,Melaka Central,1129.26,...,0,Low,10.44,0,0,0,Positive,Customer appreciated quick support and confirm...,Bill Payment through Cash Deposit Machine. Red...,Not Reviewed
1498,TXN202601498,2026-05-02 02:09:00,CUST1271,ACC11013,26,Mass,Unemployed,Melaka,KLCC,2543.83,...,2,High,60.11,1,0,0,Neutral,Unusual login from foreign IP followed by high...,Local Transfer through Mobile App. Red flags c...,Closed - Suspicious
1499,TXN202601499,2026-06-15 17:19:00,CUST1154,ACC10834,32,SME,Salaried,Selangor,KLCC,20794.70,...,4,High,100.00,1,1,1,Neutral,Repeated transfers to high risk merchant categ...,Local Transfer through International Transfer....,Open

In [2]:
display(df.head(5))
display(df.tail(5))

,transaction_id,transaction_datetime,customer_id,account_id,customer_age,customer_segment,occupation,state,branch,monthly_income_myr,...,manual_red_flag_count,risk_category,anomaly_score,anomaly_or_not,fraud_label,aml_suspicious_label,sentiment_label,customer_message,investigator_note,investigation_status
0,TXN202600000,2026-01-18 19:42:00,CUST1322,ACC11122,37,Emerging Affluent,Unemployed,Kuala Lumpur,Bukit Bintang,815.28,...,1,Low,43.26,0,0,0,Neutral,Customer asked bank to verify recent activity,Local Transfer through Mobile App. Red flags c...,Not Reviewed
1,TXN202600001,2026-04-14 11:54:00,CUST1270,ACC10255,18,Mass,Self-employed,Sarawak,Kuching,8538.78,...,0,Medium,15.29,0,0,0,Positive,Customer confirmed beneficiary and transaction...,Card Purchase through Mobile App. Red flags co...,Not Reviewed
2,TXN202600002,2026-03-07 20:12:00,CUST1349,ACC10060,27,Mass,Student,Perak,Ipoh,1250.59,...,2,Low,37.80,0,0,0,Positive,Customer appreciated quick support and confirm...,Card Purchase through ATM. Red flags count: 2....,Not Reviewed
3,TXN202600003,2026-07-23 10:03:00,CUST1139,ACC10092,60,Affluent,Salaried,Melaka,Melaka Central,13357.94,...,1,Low,36.51,0,0,0,Positive,Customer confirmed beneficiary and transaction...,Wallet Top-up through International Transfer. ...,Closed - Normal
4,TXN202600004,2026-05-30 18:36:00,CUST1215,ACC10744,26,SME,Retired,Selangor,Kuching,24430.85,...,0,Medium,16.68,0,0,0,Neutral,Customer asked for account activity summary,Cash Deposit through Online Banking. Red flags...,Not Reviewed

,transaction_id,transaction_datetime,customer_id,account_id,customer_age,customer_segment,occupation,state,branch,monthly_income_myr,...,manual_red_flag_count,risk_category,anomaly_score,anomaly_or_not,fraud_label,aml_suspicious_label,sentiment_label,customer_message,investigator_note,investigation_status
1495,TXN202601495,2026-06-11 06:08:00,CUST1334,ACC10080,33,Private Banking,Salaried,Perak,Melaka Central,23431.64,...,1,Low,15.17,0,0,0,Neutral,Customer provided documents for normal verific...,Local Transfer through Card POS. Red flags cou...,Closed - False Positive
1496,TXN202601496,2026-03-01 16:58:00,CUST1109,ACC10478,42,Mass,Business Owner,Negeri Sembilan,Johor Bahru,7870.29,...,0,Medium,11.34,0,0,0,Neutral,Customer asked for account activity summary,Cash Deposit through Card POS. Red flags count...,Closed - Normal
1497,TXN202601497,2026-04-15 14:00:00,CUST1035,ACC10148,50,Mass,Salaried,Kuala Lumpur,Melaka Central,1129.26,...,0,Low,10.44,0,0,0,Positive,Customer appreciated quick support and confirm...,Bill Payment through Cash Deposit Machine. Red...,Not Reviewed
1498,TXN202601498,2026-05-02 02:09:00,CUST1271,ACC11013,26,Mass,Unemployed,Melaka,KLCC,2543.83,...,2,High,60.11,1,0,0,Neutral,Unusual login from foreign IP followed by high...,Local Transfer through Mobile App. Red flags c...,Closed - Suspicious
1499,TXN202601499,2026-06-15 17:19:00,CUST1154,ACC10834,32,SME,Salaried,Selangor,KLCC,20794.70,...,4,High,100.00,1,1,1,Neutral,Repeated transfers to high risk merchant categ...,Local Transfer through International Transfer....,Open

In [3]:
df.shape

(1500, 44)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 44 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   transaction_id                 1500 non-null   str
 1   transaction_datetime           1500 non-null   str
 2   customer_id                    1500 non-null   str
 3   account_id                     1500 non-null   str
 4   customer_age                   1500 non-null   int64
 5   customer_segment               1500 non-null   str
 6   occupation                     1470 non-null   str
 7   state                          1500 non-null   str
 8   branch                         1500 non-null   str
 9   monthly_income_myr             1500 non-null   float64
 10  account_age_days               1500 non-null   int64
 11  kyc_status                     1470 non-null   str
 12  transaction_type               1500 non-null   str
 13  channel                        1500 non-null   str
 14  transaction_amount_myr         1500 non-null   float64
 15  balance_before_myr             1500 non-null   float64
 16  balance_after_myr              1500 non-null   float64
 17  previous_30d_txn_count         1500 non-null   int64
 18  previous_30d_total_amount_myr  1500 non-null   float64
 19  merchant_category              1470 non-null   str
 20  device_type                    1470 non-null   str
 21  ip_country                     1470 non-null   str
 22  destination_country            1500 non-null   str
 23  failed_login_count_24h         1500 non-null   int64
 24  round_amount_flag              1500 non-null   int64
 25  unusual_time_flag              1500 non-null   int64
 26  cross_border_flag              1500 non-null   int64
 27  sanctioned_country_flag        1500 non-null   int64
 28  high_risk_merchant_flag        1500 non-null   int64
 29  income_mismatch_flag           1500 non-null   int64
 30  structuring_flag               1500 non-null   int64
 31  velocity_flag                  1500 non-null   int64
 32  new_account_high_value_flag    1500 non-null   int64
 33  geo_mismatch_flag              1500 non-null   int64
 34  manual_red_flag_count          1500 non-null   int64
 35  risk_category                  1500 non-null   str
 36  anomaly_score                  1500 non-null   float64
 37  anomaly_or_not                 1500 non-null   int64
 38  fraud_label                    1500 non-null   int64
 39  aml_suspicious_label           1500 non-null   int64
 40  sentiment_label                1500 non-null   str
 41  customer_message               1470 non-null   str
 42  investigator_note              1500 non-null   str
 43  investigation_status           1500 non-null   str
dtypes: float64(6), int64(18), str(20)
memory usage: 515.8 KB

In [5]:
df.describe()

,customer_age,monthly_income_myr,account_age_days,transaction_amount_myr,balance_before_myr,balance_after_myr,previous_30d_txn_count,previous_30d_total_amount_myr,failed_login_count_24h,round_amount_flag,...,income_mismatch_flag,structuring_flag,velocity_flag,new_account_high_value_flag,geo_mismatch_flag,manual_red_flag_count,anomaly_score,anomaly_or_not,fraud_label,aml_suspicious_label
count,1500.00000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.00000,...,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000,1500.000000
mean,38.75600,10097.207700,690.075333,5180.085887,16135.575880,16474.062667,33.028667,16053.680520,2.308667,0.17800,...,0.094000,0.028000,0.076667,0.006667,0.121333,1.453333,48.567727,0.344000,0.085333,0.168000
std,11.39721,10300.168134,731.934866,21755.509560,19875.770818,20788.649906,31.621888,13956.918649,5.019780,0.38264,...,0.291926,0.165028,0.266151,0.081404,0.326623,1.158469,27.610773,0.475199,0.279470,0.373991
min,18.00000,300.000000,1.000000,105.580000,257.270000,0.000000,11.000000,1299.840000,0.000000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,31.00000,3584.682500,156.750000,787.632500,5203.152500,4377.442500,21.000000,7055.025000,0.000000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,26.325000,0.000000,0.000000,0.000000
50%,38.00000,7171.035000,461.000000,1503.465000,10088.305000,10198.345000,25.000000,11851.705000,1.000000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,46.905000,0.000000,0.000000,0.000000
75%,47.00000,11462.110000,968.250000,3572.342500,19050.160000,20610.472500,28.000000,20093.195000,2.000000,0.00000,...,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,67.577500,1.000000,0.000000,0.000000
max,76.00000,70877.670000,5227.000000,600425.400000,259952.590000,250213.300000,198.000000,142734.710000,31.000000,1.00000,...,1.000000,1.000000,1.000000,1.000000,1.000000,6.000000,100.000000,1.000000,1.000000,1.000000

In [6]:
df.columns

Index(['transaction_id', 'transaction_datetime', 'customer_id', 'account_id',
       'customer_age', 'customer_segment', 'occupation', 'state', 'branch',
       'monthly_income_myr', 'account_age_days', 'kyc_status',
       'transaction_type', 'channel', 'transaction_amount_myr',
       'balance_before_myr', 'balance_after_myr', 'previous_30d_txn_count',
       'previous_30d_total_amount_myr', 'merchant_category', 'device_type',
       'ip_country', 'destination_country', 'failed_login_count_24h',
       'round_amount_flag', 'unusual_time_flag', 'cross_border_flag',
       'sanctioned_country_flag', 'high_risk_merchant_flag',
       'income_mismatch_flag', 'structuring_flag', 'velocity_flag',
       'new_account_high_value_flag', 'geo_mismatch_flag',
       'manual_red_flag_count', 'risk_category', 'anomaly_score',
       'anomaly_or_not', 'fraud_label', 'aml_suspicious_label',
       'sentiment_label', 'customer_message', 'investigator_note',
       'investigation_status'],
      dtype='str')

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df.isnull().sum()

transaction_id                    0
transaction_datetime              0
customer_id                       0
account_id                        0
customer_age                      0
customer_segment                  0
occupation                       30
state                             0
branch                            0
monthly_income_myr                0
account_age_days                  0
kyc_status                       30
transaction_type                  0
channel                           0
transaction_amount_myr            0
balance_before_myr                0
balance_after_myr                 0
previous_30d_txn_count            0
previous_30d_total_amount_myr     0
merchant_category                30
device_type                      30
ip_country                       30
destination_country               0
failed_login_count_24h            0
round_amount_flag                 0
unusual_time_flag                 0
cross_border_flag                 0
sanctioned_country_flag           0
high_risk_merchant_flag           0
income_mismatch_flag              0
structuring_flag                  0
velocity_flag                     0
new_account_high_value_flag       0
geo_mismatch_flag                 0
manual_red_flag_count             0
risk_category                     0
anomaly_score                     0
anomaly_or_not                    0
fraud_label                       0
aml_suspicious_label              0
sentiment_label                   0
customer_message                 30
investigator_note                 0
investigation_status              0
dtype: int64

In [4]:
df[df["occupation"].isnull()]

,transaction_id,transaction_datetime,customer_id,account_id,customer_age,customer_segment,occupation,state,branch,monthly_income_myr,...,manual_red_flag_count,risk_category,anomaly_score,anomaly_or_not,fraud_label,aml_suspicious_label,sentiment_label,customer_message,investigator_note,investigation_status
142,TXN202600142,2026-06-28 23:39:00,CUST1133,ACC10513,52,Mass,NaN,Johor,Kuantan,1320.87,...,1,Low,38.54,0,0,0,Neutral,Customer asked for account activity summary,Local Transfer through Mobile App. Red flags c...,Not Reviewed
183,TXN202600183,2026-05-26 10:15:00,CUST1084,ACC10982,27,Mass,NaN,Kelantan,Ipoh,8245.97,...,0,Low,21.36,0,0,0,Neutral,Customer asked for account activity summary,Cash Deposit through Mobile App. Red flags cou...,Closed - Normal
185,TXN202600185,2026-04-11 11:54:00,CUST1325,ACC10820,31,Mass,NaN,Sabah,Kuching,4849.38,...,1,Low,21.56,0,0,0,Positive,Customer confirmed transaction and no issue re...,Cash Withdrawal through Mobile App. Red flags ...,Not Reviewed
276,TXN202600276,2026-05-11 03:29:00,CUST1187,ACC10463,58,SME,NaN,Penang,Kota Bharu,27150.86,...,2,High,62.61,1,0,0,Negative,Customer is upset about unknown debit and poss...,Card Purchase through Branch. Red flags count:...,Closed - False Positive
294,TXN202600294,2026-01-15 11:30:00,CUST1216,ACC10972,51,SME,NaN,Pahang,Kuantan,24393.62,...,0,Medium,10.73,0,0,0,Positive,Customer says payment was expected and genuine,Local Transfer through Mobile App. Red flags c...,Not Reviewed
483,TXN202600483,2026-01-15 11:48:00,CUST1229,ACC10256,58,Mass,NaN,Sarawak,Shah Alam,8445.37,...,1,Low,19.02,0,0,0,Neutral,Customer wants clarification on transfer status,Bill Payment through Mobile App. Red flags cou...,Not Reviewed
611,TXN202600611,2026-05-14 05:32:00,CUST1186,ACC10482,39,Emerging Affluent,NaN,Perak,Shah Alam,2240.66,...,0,Low,9.34,0,0,0,Neutral,Customer asked for account activity summary,Cash Deposit through ATM. Red flags count: 0. ...,Not Reviewed
630,TXN202600630,2026-03-23 08:35:00,CUST1301,ACC11154,39,Emerging Affluent,NaN,Negeri Sembilan,Shah Alam,1209.01,...,0,Low,11.59,0,0,0,Positive,Customer confirmed transaction and no issue re...,Local Transfer through Mobile App. Red flags c...,Not Reviewed
643,TXN202600643,2026-07-24 15:04:00,CUST1213,ACC10809,49,Mass,NaN,Kuala Lumpur,Kuantan,5742.17,...,1,Medium,28.71,0,0,0,Positive,Customer is satisfied after clarification from...,Local Transfer through Branch. Red flags count...,Not Reviewed
664,TXN202600664,2026-01-31 11:52:00,CUST1119,ACC10755,45,Mass,NaN,Terengganu,George Town,2266.81,...,0,Low,12.37,0,0,0,Neutral,Customer asked for account activity summary,Local Transfer through ATM. Red flags count: 0...,Not Reviewed
730,TXN202600730,2026-01-31 18:46:00,CUST1320,ACC10679,43,Emerging Affluent,NaN,Pahang,Kuantan,700.00,...,2,High,79.13,1,0,1,Negative,Customer says card was used without permission,Loan Repayment through Cash Deposit Machine. R...,Closed - False Positive
786,TXN202600786,2026-03-30 18:51:00,CUST1119,ACC10988,46,Emerging Affluent,NaN,Terengganu,Kota Kinabalu,7329.09,...,2,Low,59.35,0,0,0,Neutral,Customer asked bank to verify recent activity,Loan Repayment through Online Banking. Red fla...,Not Reviewed
867,TXN202600867,2026-02-21 09:41:00,CUST1131,ACC10599,23,Mass,NaN,Sarawak,Kota Bharu,8094.21,...,2,Medium,65.45,1,0,0,Neutral,Unusual login from foreign IP followed by high...,Cash Deposit through International Transfer. R...,Closed - False Positive
893,TXN202600893,2026-02-23 22:57:00,CUST1088,ACC11047,18,Affluent,NaN,Melaka,Ipoh,2360.50,...,3,Medium,98.79,1,0,0,Neutral,Multiple small cash deposits below reporting l...,Card Purchase through Mobile App. Red flags co...,Open
911,TXN202600911,2026-05-22 07:03:00,CUST1344,ACC10451,54,Mass,NaN,Sabah,Melaka Central,2051.25,...,1,Low,35.24,0,0,0,Positive,Customer confirmed transaction and no issue re...,Local Transfer through Branch. Red flags count...,Not Reviewed
930,TXN202600930,2026-05-08 13:05:00,CUST1121,ACC11120,44,Mass,NaN,Perak,Melaka Central,10913.93,...,0,Low,23.08,0,0,0,Positive,Customer appreciated quick support and confirm...,Local Transfer through Branch. Red flags count...,Not Reviewed
946,TXN202600946,2026-01-04 21:42:00,CUST1348,ACC11106,31,Affluent,NaN,Kuala Lumpur,Petaling Jaya,2447.73,...,1,Low,51.41,0,0,0,Positive,Customer appreciated quick support and confirm...,Local Transfer through International Transfer....,Not Reviewed
1134,TXN202601134,2026-01-15 12:44:00,CUST1086,ACC10382,49,Mass,NaN,Perak,Bukit Bintang,9174.09,...,1,Medium,49.61,0,0,0,Neutral,Customer provided documents for normal verific...,Local Transfer through ATM. Red flags count: 1...,Not Reviewed
1165,TXN202601165,2026-04-26 09:26:00,CUST1286,ACC10990,42,Mass,NaN,Sabah,Johor Bahru,2930.85,...,1,Medium,31.43,0,0,0,Positive,Customer confirmed beneficiary and transaction...,Local Transfer through ATM. Red flags count: 1...,Not Reviewed
1215,TXN202601215,2026-07-22 19:58:00,CUST1027,ACC11105,25,Emerging Affluent,NaN,Penang,Johor Bahru,8238.69,...,0,Medium,8.49,0,0,0,Neutral,Customer wants clarification on transfer status,Bill Payment through Online Banking. Red flags...,Closed - Normal
1287,TXN202601287,2026-01-19 08:31:00,CUST1216,ACC10771,28,Affluent,NaN,Melaka,Kuantan,7422.41,...,1,Low,22.65,0,0,0,Positive,Customer appreciated quick support and confirm...,Card Purchase through Branch. Red flags count:...,Not Reviewed
1308,TXN202601308,2026-06-23 07:03:00,CUST1001,ACC11082,49,Emerging Affluent,NaN,Johor,Kuantan,10513.33,...,1,Low,11.20,0,0,0,Positive,Customer confirmed beneficiary and transaction...,Cash Deposit through Online Banking. Red flags...,Closed - False Positive
1354,TXN202601354,2026-06-26 15:20:00,CUST1292,ACC10609,21,Private Banking,NaN,Terengganu,KLCC,21490.72,...,0,Medium,3.02,0,0,0,Neutral,Customer provided documents for normal verific...,Card Purchase through Mobile App. Red flags co...,Not Reviewed
1378,TXN202601378,2026-03-24 11:52:00,CUST1171,ACC11129,64,Emerging Affluent,NaN,Pahang,Melaka Central,2770.79,...,0,Low,12.87,0,0,0,Positive,Customer is satisfied after clarification from...,Local Transfer through ATM. Red flags count: 0...,Not Reviewed
1452,TXN202601452,2026-03-14 14:47:00,CUST1333,ACC10373,33,Mass,NaN,Sabah,KLCC,6617.72,...,2,High,63.74,1,0,0,Neutral,Repeated transfers to high risk merchant categ...,Cash Withdrawal through Branch. Red flags coun...,Escalated
1477,TXN202601477,2026-05-17 08:35:00,CUST1049,ACC10099,65,Mass,NaN,Selangor,Petaling Jaya,1680.88,...,3,Medium,88.25,1,0,1,Negative,Customer is upset about unknown debit and poss...,Local Transfer through Cash Deposit Machine. R...,Escalated
1478,TXN202601478,2026-07-21 13:02:00,CUST1029,ACC11222,51,Mass,NaN,Sarawak,Johor Bahru,1760.22,...,0,Low,13.09,0,0,0,Neutral,Customer asked for account activity summary,Local Transfer through Mobile App. Red flags c...,Closed - Normal
1488,TXN202601488,2026-06-09 14:22:00,CUST1308,ACC10227,49,Mass,NaN,Selangor,Ipoh,2833.53,...,0,Low,10.88,0,0,0,Neutral,Customer provided documents for normal verific...,Loan Repayment through ATM. Red flags count: 0...,Closed - Normal
1490,TXN202601490,2026-06-17 01:42:00,CUST1185,ACC10420,33,Emerging Affluent,NaN,Perak,Johor Bahru,6930.30,...,2,Low,59.10,0,0,0,Neutral,Customer asked for account activity summary,International Transfer through Branch. Red fla...,Not Reviewed
1494,TXN202601494,2026-06-12 11:44:00,CUST1008,ACC10464,21,Affluent,NaN,Terengganu,Johor Bahru,3805.04,...,0,Low,19.19,0,0,0,Positive,Customer says payment was expected and genuine,Local Transfer through ATM. Red flags count: 0...,Not Reviewed

In [6]:
df["occupation"] = df["occupation"].fillna("Unknown")
df["kyc_status"] = df["kyc_status"].fillna("Unknown")
df["merchant_category"] = df["merchant_category"].fillna("Unknown")
df["device_type"] = df["device_type"].fillna("Unknown")
df["ip_country"] = df["ip_country"].fillna("Unknown")
df["customer_message"] = df["customer_message"].fillna("Unknown")

In [7]:
df.isnull().sum()

transaction_id                   0
transaction_datetime             0
customer_id                      0
account_id                       0
customer_age                     0
customer_segment                 0
occupation                       0
state                            0
branch                           0
monthly_income_myr               0
account_age_days                 0
kyc_status                       0
transaction_type                 0
channel                          0
transaction_amount_myr           0
balance_before_myr               0
balance_after_myr                0
previous_30d_txn_count           0
previous_30d_total_amount_myr    0
merchant_category                0
device_type                      0
ip_country                       0
destination_country              0
failed_login_count_24h           0
round_amount_flag                0
unusual_time_flag                0
cross_border_flag                0
sanctioned_country_flag          0
high_risk_merchant_flag          0
income_mismatch_flag             0
structuring_flag                 0
velocity_flag                    0
new_account_high_value_flag      0
geo_mismatch_flag                0
manual_red_flag_count            0
risk_category                    0
anomaly_score                    0
anomaly_or_not                   0
fraud_label                      0
aml_suspicious_label             0
sentiment_label                  0
customer_message                 0
investigator_note                0
investigation_status             0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.dtypes

transaction_id                       str
transaction_datetime                 str
customer_id                          str
account_id                           str
customer_age                       int64
customer_segment                     str
occupation                           str
state                                str
branch                               str
monthly_income_myr               float64
account_age_days                   int64
kyc_status                           str
transaction_type                     str
channel                              str
transaction_amount_myr           float64
balance_before_myr               float64
balance_after_myr                float64
previous_30d_txn_count             int64
previous_30d_total_amount_myr    float64
merchant_category                    str
device_type                          str
ip_country                           str
destination_country                  str
failed_login_count_24h             int64
round_amount_flag                  int64
unusual_time_flag                  int64
cross_border_flag                  int64
sanctioned_country_flag            int64
high_risk_merchant_flag            int64
income_mismatch_flag               int64
structuring_flag                   int64
velocity_flag                      int64
new_account_high_value_flag        int64
geo_mismatch_flag                  int64
manual_red_flag_count              int64
risk_category                        str
anomaly_score                    float64
anomaly_or_not                     int64
fraud_label                        int64
aml_suspicious_label               int64
sentiment_label                      str
customer_message                     str
investigator_note                    str
investigation_status                 str
dtype: object

In [10]:
df["transaction_datetime"] = pd.to_datetime(df["transaction_datetime"])

In [11]:
df.dtypes

transaction_id                              str
transaction_datetime             datetime64[us]
customer_id                                 str
account_id                                  str
customer_age                              int64
customer_segment                            str
occupation                                  str
state                                       str
branch                                      str
monthly_income_myr                      float64
account_age_days                          int64
kyc_status                                  str
transaction_type                            str
channel                                     str
transaction_amount_myr                  float64
balance_before_myr                      float64
balance_after_myr                       float64
previous_30d_txn_count                    int64
previous_30d_total_amount_myr           float64
merchant_category                           str
device_type                                 str
ip_country                                  str
destination_country                         str
failed_login_count_24h                    int64
round_amount_flag                         int64
unusual_time_flag                         int64
cross_border_flag                         int64
sanctioned_country_flag                   int64
high_risk_merchant_flag                   int64
income_mismatch_flag                      int64
structuring_flag                          int64
velocity_flag                             int64
new_account_high_value_flag               int64
geo_mismatch_flag                         int64
manual_red_flag_count                     int64
risk_category                               str
anomaly_score                           float64
anomaly_or_not                            int64
fraud_label                               int64
aml_suspicious_label                      int64
sentiment_label                             str
customer_message                            str
investigator_note                           str
investigation_status                        str
dtype: object

In [12]:
df["transaction_datetime"].isnull().sum()

np.int64(0)

In [13]:
df

,transaction_id,transaction_datetime,customer_id,account_id,customer_age,customer_segment,occupation,state,branch,monthly_income_myr,...,manual_red_flag_count,risk_category,anomaly_score,anomaly_or_not,fraud_label,aml_suspicious_label,sentiment_label,customer_message,investigator_note,investigation_status
0,TXN202600000,2026-01-18 19:42:00,CUST1322,ACC11122,37,Emerging Affluent,Unemployed,Kuala Lumpur,Bukit Bintang,815.28,...,1,Low,43.26,0,0,0,Neutral,Customer asked bank to verify recent activity,Local Transfer through Mobile App. Red flags c...,Not Reviewed
1,TXN202600001,2026-04-14 11:54:00,CUST1270,ACC10255,18,Mass,Self-employed,Sarawak,Kuching,8538.78,...,0,Medium,15.29,0,0,0,Positive,Customer confirmed beneficiary and transaction...,Card Purchase through Mobile App. Red flags co...,Not Reviewed
2,TXN202600002,2026-03-07 20:12:00,CUST1349,ACC10060,27,Mass,Student,Perak,Ipoh,1250.59,...,2,Low,37.80,0,0,0,Positive,Customer appreciated quick support and confirm...,Card Purchase through ATM. Red flags count: 2....,Not Reviewed
3,TXN202600003,2026-07-23 10:03:00,CUST1139,ACC10092,60,Affluent,Salaried,Melaka,Melaka Central,13357.94,...,1,Low,36.51,0,0,0,Positive,Customer confirmed beneficiary and transaction...,Wallet Top-up through International Transfer. ...,Closed - Normal
4,TXN202600004,2026-05-30 18:36:00,CUST1215,ACC10744,26,SME,Retired,Selangor,Kuching,24430.85,...,0,Medium,16.68,0,0,0,Neutral,Customer asked for account activity summary,Cash Deposit through Online Banking. Red flags...,Not Reviewed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,TXN202601495,2026-06-11 06:08:00,CUST1334,ACC10080,33,Private Banking,Salaried,Perak,Melaka Central,23431.64,...,1,Low,15.17,0,0,0,Neutral,Customer provided documents for normal verific...,Local Transfer through Card POS. Red flags cou...,Closed - False Positive
1496,TXN202601496,2026-03-01 16:58:00,CUST1109,ACC10478,42,Mass,Business Owner,Negeri Sembilan,Johor Bahru,7870.29,...,0,Medium,11.34,0,0,0,Neutral,Customer asked for account activity summary,Cash Deposit through Card POS. Red flags count...,Closed - Normal
1497,TXN202601497,2026-04-15 14:00:00,CUST1035,ACC10148,50,Mass,Salaried,Kuala Lumpur,Melaka Central,1129.26,...,0,Low,10.44,0,0,0,Positive,Customer appreciated quick support and confirm...,Bill Payment through Cash Deposit Machine. Red...,Not Reviewed
1498,TXN202601498,2026-05-02 02:09:00,CUST1271,ACC11013,26,Mass,Unemployed,Melaka,KLCC,2543.83,...,2,High,60.11,1,0,0,Neutral,Unusual login from foreign IP followed by high...,Local Transfer through Mobile App. Red flags c...,Closed - Suspicious
1499,TXN202601499,2026-06-15 17:19:00,CUST1154,ACC10834,32,SME,Salaried,Selangor,KLCC,20794.70,...,4,High,100.00,1,1,1,Neutral,Repeated transfers to high risk merchant categ...,Local Transfer through International Transfer....,Open

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df["customer_segment"].unique()

<StringArray>
['Emerging Affluent', 'Mass', 'Affluent', 'SME', 'Private Banking']
Length: 5, dtype: str

In [17]:
df["transaction_type"].unique()

<StringArray>
[        'Local Transfer',          'Card Purchase',          'Wallet Top-up',
           'Cash Deposit',           'Bill Payment',         'Loan Repayment',
 'International Transfer',        'Cash Withdrawal']
Length: 8, dtype: str

In [18]:
df["channel"].unique()

<StringArray>
[            'Mobile App',                    'ATM', 'International Transfer',
         'Online Banking',   'Cash Deposit Machine',                 'Branch',
               'Card POS']
Length: 7, dtype: str

In [19]:
df["risk_category"].value_counts()

risk_category
Low       803
High      405
Medium    292
Name: count, dtype: int64

In [20]:
df["transaction_type"].value_counts()

transaction_type
Local Transfer            350
Card Purchase             289
Bill Payment              193
Cash Deposit              179
International Transfer    137
Cash Withdrawal           133
Wallet Top-up             119
Loan Repayment            100
Name: count, dtype: int64

In [21]:
df["transaction_amount_myr"].max()

np.float64(600425.4)

In [22]:
df["transaction_month"] = df["transaction_datetime"].dt.month

In [29]:
df

,transaction_id,transaction_datetime,customer_id,account_id,customer_age,customer_segment,occupation,state,branch,monthly_income_myr,...,risk_category,anomaly_score,anomaly_or_not,fraud_label,aml_suspicious_label,sentiment_label,customer_message,investigator_note,investigation_status,transaction_month
0,TXN202600000,2026-01-18 19:42:00,CUST1322,ACC11122,37,Emerging Affluent,Unemployed,Kuala Lumpur,Bukit Bintang,815.28,...,Low,43.26,0,0,0,Neutral,Customer asked bank to verify recent activity,Local Transfer through Mobile App. Red flags c...,Not Reviewed,1
1,TXN202600001,2026-04-14 11:54:00,CUST1270,ACC10255,18,Mass,Self-employed,Sarawak,Kuching,8538.78,...,Medium,15.29,0,0,0,Positive,Customer confirmed beneficiary and transaction...,Card Purchase through Mobile App. Red flags co...,Not Reviewed,4
2,TXN202600002,2026-03-07 20:12:00,CUST1349,ACC10060,27,Mass,Student,Perak,Ipoh,1250.59,...,Low,37.80,0,0,0,Positive,Customer appreciated quick support and confirm...,Card Purchase through ATM. Red flags count: 2....,Not Reviewed,3
3,TXN202600003,2026-07-23 10:03:00,CUST1139,ACC10092,60,Affluent,Salaried,Melaka,Melaka Central,13357.94,...,Low,36.51,0,0,0,Positive,Customer confirmed beneficiary and transaction...,Wallet Top-up through International Transfer. ...,Closed - Normal,7
4,TXN202600004,2026-05-30 18:36:00,CUST1215,ACC10744,26,SME,Retired,Selangor,Kuching,24430.85,...,Medium,16.68,0,0,0,Neutral,Customer asked for account activity summary,Cash Deposit through Online Banking. Red flags...,Not Reviewed,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1495,TXN202601495,2026-06-11 06:08:00,CUST1334,ACC10080,33,Private Banking,Salaried,Perak,Melaka Central,23431.64,...,Low,15.17,0,0,0,Neutral,Customer provided documents for normal verific...,Local Transfer through Card POS. Red flags cou...,Closed - False Positive,6
1496,TXN202601496,2026-03-01 16:58:00,CUST1109,ACC10478,42,Mass,Business Owner,Negeri Sembilan,Johor Bahru,7870.29,...,Medium,11.34,0,0,0,Neutral,Customer asked for account activity summary,Cash Deposit through Card POS. Red flags count...,Closed - Normal,3
1497,TXN202601497,2026-04-15 14:00:00,CUST1035,ACC10148,50,Mass,Salaried,Kuala Lumpur,Melaka Central,1129.26,...,Low,10.44,0,0,0,Positive,Customer appreciated quick support and confirm...,Bill Payment through Cash Deposit Machine. Red...,Not Reviewed,4
1498,TXN202601498,2026-05-02 02:09:00,CUST1271,ACC11013,26,Mass,Unemployed,Melaka,KLCC,2543.83,...,High,60.11,1,0,0,Neutral,Unusual login from foreign IP followed by high...,Local Transfer through Mobile App. Red flags c...,Closed - Suspicious,5
1499,TXN202601499,2026-06-15 17:19:00,CUST1154,ACC10834,32,SME,Salaried,Selangor,KLCC,20794.70,...,High,100.00,1,1,1,Neutral,Repeated transfers to high risk merchant categ...,Local Transfer through International Transfer....,Open,6

In [24]:
df.groupby("transaction_type")["transaction_amount_myr"].mean()

transaction_type
Bill Payment              3873.200311
Card Purchase             2556.979862
Cash Deposit              5092.361453
Cash Withdrawal           4696.201203
International Transfer    8649.275693
Loan Repayment            5959.343900
Local Transfer            5475.346314
Wallet Top-up             8825.631597
Name: transaction_amount_myr, dtype: float64

In [31]:
df["balance_change"] = (df["balance_after_myr"] - df["balance_before_myr"])

In [32]:
df[["balance_before_myr","transaction_amount_myr","balance_after_myr","balance_change"]].head()

,balance_before_myr,transaction_amount_myr,balance_after_myr,balance_change
0,25020.79,764.30,25785.09,764.30
1,5375.93,2214.59,3161.34,-2214.59
2,12742.00,710.49,13452.49,710.49
3,17464.30,1630.74,19095.04,1630.74
4,3995.31,1644.29,5639.60,1644.29