In [1]:
import pandas as pd
df = pd.read_csv('pokemon_data.csv')
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [2]:
display(df.head(5))
display(df.tail(5))

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [3]:
df.shape

(800, 12)

In [4]:
list[df.columns]

list[Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   HP          800 non-null    int64
 5   Attack      800 non-null    int64
 6   Defense     800 non-null    int64
 7   Sp. Atk     800 non-null    int64
 8   Sp. Def     800 non-null    int64
 9   Speed       800 non-null    int64
 10  Generation  800 non-null    int64
 11  Legendary   800 non-null    bool
dtypes: bool(1), int64(8), object(3)
memory usage: 69.7+ KB

In [7]:
df.describe()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [8]:
df.describe(include='object')

             Name Type 1  Type 2
count         800    800     414
unique        800     18      18
top     Bulbasaur  Water  Flying
freq            1    112      97

In [9]:
df.memory_usage(deep=True)

Index           132
#              6400
Name          46303
Type 1        43408
Type 2        34978
HP             6400
Attack         6400
Defense        6400
Sp. Atk        6400
Sp. Def        6400
Speed          6400
Generation     6400
Legendary       800
dtype: int64

In [11]:
speed_df = df.copy()
speed_df.head(5)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [10]:
import pandas as pd
df = pd.read_csv('pokemon_data.csv')
df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [12]:
df.sample(10, random_state=4)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
267,248,Tyranitar,Rock,Dark,100,134,110,95,100,61,2,False
577,518,Musharna,Psychic,NaN,116,55,85,107,95,29,5,False
464,417,Pachirisu,Electric,NaN,60,45,70,45,90,95,4,False
722,654,Braixen,Fire,NaN,59,59,58,90,70,73,6,False
685,624,Pawniard,Dark,Steel,45,85,70,40,40,60,5,False
669,608,Lampent,Ghost,Fire,60,40,60,95,60,55,5,False
791,715,Noivern,Flying,Dragon,85,70,80,97,80,123,6,False
718,650,Chespin,Grass,NaN,56,61,65,48,45,38,6,False
788,712,Bergmite,Ice,NaN,55,69,85,32,35,28,6,False
147,136,Flareon,Fire,NaN,65,130,60,95,110,65,1,False

In [18]:
print(df[['Name', 'Type 1', 'Type 2']])

                      Name   Type 1  Type 2
0                Bulbasaur    Grass  Poison
1                  Ivysaur    Grass  Poison
2                 Venusaur    Grass  Poison
3    VenusaurMega Venusaur    Grass  Poison
4               Charmander     Fire     NaN
..                     ...      ...     ...
795                Diancie     Rock   Fairy
796    DiancieMega Diancie     Rock   Fairy
797    HoopaHoopa Confined  Psychic   Ghost
798     HoopaHoopa Unbound  Psychic    Dark
799              Volcanion     Fire   Water

[800 rows x 3 columns]

In [19]:
print(df.iloc[0:11])

    #                       Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0   1                  Bulbasaur  Grass  Poison  45      49       49       65
1   2                    Ivysaur  Grass  Poison  60      62       63       80
2   3                   Venusaur  Grass  Poison  80      82       83      100
3   3      VenusaurMega Venusaur  Grass  Poison  80     100      123      122
4   4                 Charmander   Fire     NaN  39      52       43       60
5   5                 Charmeleon   Fire     NaN  58      64       58       80
6   6                  Charizard   Fire  Flying  78      84       78      109
7   6  CharizardMega Charizard X   Fire  Dragon  78     130      111      130
8   6  CharizardMega Charizard Y   Fire  Flying  78     104       78      159
9   7                   Squirtle  Water     NaN  44      48       65       50
10  8                  Wartortle  Water     NaN  59      63       80       65

    Sp. Def  Speed  Generation  Legendary
0        65     45           1      False
1        80     60           1      False
2       100     80           1      False
3       120     80           1      False
4        50     65           1      False
5        65     80           1      False
6        85    100           1      False
7        85    100           1      False
8       115    100           1      False
9        64     43           1      False
10       80     58           1      False

In [21]:
df.iloc[20:30 , 6:2]

Empty DataFrame
Columns: []
Index: [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]

In [22]:
df.loc[df['Type 1'] == "Rock"]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
80,74,Geodude,Rock,Ground,40,80,100,30,30,20,1,False
81,75,Graveler,Rock,Ground,55,95,115,45,45,35,1,False
82,76,Golem,Rock,Ground,80,120,130,55,65,45,1,False
103,95,Onix,Rock,Ground,35,45,160,30,45,70,1,False
149,138,Omanyte,Rock,Water,35,40,100,90,55,35,1,False
150,139,Omastar,Rock,Water,70,60,125,115,70,55,1,False
151,140,Kabuto,Rock,Water,30,80,90,55,45,55,1,False
152,141,Kabutops,Rock,Water,60,115,105,65,70,80,1,False
153,142,Aerodactyl,Rock,Flying,80,105,65,60,75,130,1,False
154,142,AerodactylMega Aerodactyl,Rock,Flying,80,135,85,70,95,150,1,False
200,185,Sudowoodo,Rock,NaN,70,100,115,30,65,30,2,False
265,246,Larvitar,Rock,Ground,50,64,50,45,50,41,2,False
266,247,Pupitar,Rock,Ground,70,84,70,65,70,51,2,False
267,248,Tyranitar,Rock,Dark,100,134,110,95,100,61,2,False
268,248,TyranitarMega Tyranitar,Rock,Dark,100,164,150,95,120,71,2,False
323,299,Nosepass,Rock,NaN,30,45,135,45,90,30,3,False
369,337,Lunatone,Rock,Psychic,70,55,65,95,85,70,3,False
370,338,Solrock,Rock,Psychic,70,95,85,55,65,70,3,False
377,345,Lileep,Rock,Grass,66,41,77,61,87,23,3,False
378,346,Cradily,Rock,Grass,86,81,97,81,107,43,3,False
379,347,Anorith,Rock,Bug,45,95,50,40,50,75,3,False
380,348,Armaldo,Rock,Bug,75,125,100,70,80,45,3,False
414,377,Regirock,Rock,NaN,80,100,200,50,100,50,3,True
453,408,Cranidos,Rock,NaN,67,125,40,30,30,58,4,False
454,409,Rampardos,Rock,NaN,97,165,60,65,50,58,4,False
455,410,Shieldon,Rock,Steel,30,42,118,42,88,30,4,False
456,411,Bastiodon,Rock,Steel,60,52,168,47,138,30,4,False
486,438,Bonsly,Rock,NaN,50,80,95,10,45,10,4,False
528,476,Probopass,Rock,Steel,60,55,145,75,150,40,4,False
583,524,Roggenrola,Rock,NaN,55,75,85,25,25,15,5,False
584,525,Boldore,Rock,NaN,70,105,105,50,40,20,5,False
585,526,Gigalith,Rock,NaN,85,135,130,60,80,25,5,False
627,566,Archen,Rock,Flying,55,112,45,74,45,70,5,False
628,567,Archeops,Rock,Flying,75,140,65,112,65,110,5,False
700,639,Terrakion,Rock,Fighting,91,129,90,72,90,108,5,True
758,688,Binacle,Rock,Water,42,52,67,39,56,50,6,False
759,689,Barbaracle,Rock,Water,72,105,115,54,86,68,6,False
766,696,Tyrunt,Rock,Dragon,58,89,77,45,45,48,6,False
767,697,Tyrantrum,Rock,Dragon,82,121,119,69,59,71,6,False
768,698,Amaura,Rock,Ice,77,59,50,67,63,46,6,False
769,699,Aurorus,Rock,Ice,123,77,72,99,92,58,6,False
773,703,Carbink,Rock,Fairy,50,50,150,50,150,50,6,False
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True

In [23]:
df.loc[df['Attack'] > 100]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,79,103,120,135,115,78,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,65,150,40,15,80,145,1,False
39,34,Nidoking,Poison,Ground,81,102,77,85,75,85,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
793,717,Yveltal,Dark,Flying,126,131,95,131,98,99,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [24]:
df.loc[(df['Attack'] > 100) & df['Legendary'] == True]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
162,150,Mewtwo,Psychic,NaN,106,110,90,154,90,130,1,True
163,150,MewtwoMega Mewtwo X,Psychic,Fighting,106,190,100,154,100,130,1,True
164,150,MewtwoMega Mewtwo Y,Psychic,NaN,106,150,70,194,120,140,1,True
263,244,Entei,Fire,NaN,115,115,85,90,75,100,2,True
270,250,Ho-oh,Fire,Flying,106,130,90,110,154,90,2,True
420,381,LatiosMega Latios,Dragon,Psychic,80,130,100,160,120,110,3,True
422,382,KyogrePrimal Kyogre,Water,NaN,100,150,90,180,160,90,3,True
423,383,Groudon,Ground,NaN,100,150,140,100,90,90,3,True
424,383,GroudonPrimal Groudon,Ground,Fire,100,180,160,150,90,90,3,True
425,384,Rayquaza,Dragon,Flying,105,150,90,150,90,95,3,True
426,384,RayquazaMega Rayquaza,Dragon,Flying,105,180,100,180,100,115,3,True
428,386,DeoxysNormal Forme,Psychic,NaN,50,150,50,150,50,150,3,True
429,386,DeoxysAttack Forme,Psychic,NaN,50,180,20,180,20,150,3,True
538,481,Mesprit,Psychic,NaN,80,105,105,105,105,80,4,True
539,482,Azelf,Psychic,NaN,75,125,70,125,70,115,4,True
540,483,Dialga,Steel,Dragon,100,120,120,150,100,90,4,True
541,484,Palkia,Water,Dragon,90,120,100,150,120,100,4,True
543,486,Regigigas,Normal,NaN,110,160,110,80,110,100,4,True
545,487,GiratinaOrigin Forme,Ghost,Dragon,150,120,100,120,100,90,4,True
551,492,ShayminSky Forme,Grass,Flying,100,103,75,120,75,127,4,True
552,493,Arceus,Normal,NaN,120,120,120,120,120,120,4,True
700,639,Terrakion,Rock,Fighting,91,129,90,72,90,108,5,True
702,641,TornadusIncarnate Forme,Flying,NaN,79,115,70,125,80,111,5,True
704,642,ThundurusIncarnate Forme,Electric,Flying,79,115,70,125,80,111,5,True
705,642,ThundurusTherian Forme,Electric,Flying,79,105,70,145,80,101,5,True
706,643,Reshiram,Dragon,Fire,100,120,100,150,120,90,5,True
707,644,Zekrom,Dragon,Electric,100,150,120,120,100,90,5,True
708,645,LandorusIncarnate Forme,Ground,Flying,89,125,90,115,80,101,5,True
709,645,LandorusTherian Forme,Ground,Flying,89,145,90,105,80,91,5,True
710,646,Kyurem,Dragon,Ice,125,130,90,130,90,95,5,True
711,646,KyuremBlack Kyurem,Dragon,Ice,125,170,100,120,90,95,5,True
712,646,KyuremWhite Kyurem,Dragon,Ice,125,120,90,170,100,95,5,True
792,716,Xerneas,Fairy,NaN,126,131,95,131,98,99,6,True
793,717,Yveltal,Dark,Flying,126,131,95,131,98,99,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [32]:
df[df["Type 1"].isin(['Psychic','Fire','Dark'])]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
757,687,Malamar,Dark,Psychic,86,92,88,68,75,73,6,False
793,717,Yveltal,Dark,Flying,126,131,95,131,98,99,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [33]:
df.query('Speed > 90')

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,65,150,40,15,80,145,1,False
22,18,Pidgeot,Normal,Flying,83,80,75,70,70,101,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
791,715,Noivern,Flying,Dragon,85,70,80,97,80,123,6,False
792,716,Xerneas,Fairy,NaN,126,131,95,131,98,99,6,True
793,717,Yveltal,Dark,Flying,126,131,95,131,98,99,6,True
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True

In [34]:
df.sort_values('Name', ascending =False)

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False

In [38]:
df.sort_values(['Name', 'Type 2'], ascending =[True ,False])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True

In [41]:
df.rename(columns={'Speed':'Speed_new'})

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed_new,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [43]:
df.isnull().sum()

#               0
Name            0
Type 1          0
Type 2        386
HP              0
Attack          0
Defense         0
Sp. Atk         0
Sp. Def         0
Speed           0
Generation      0
Legendary       0
dtype: int64

In [44]:
df[df['Type 2'].isnull()]

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
9,7,Squirtle,Water,NaN,44,48,65,50,64,43,1,False
10,8,Wartortle,Water,NaN,59,63,80,65,80,58,1,False
11,9,Blastoise,Water,NaN,79,83,100,85,105,78,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
775,705,Sliggoo,Dragon,NaN,68,75,53,83,113,60,6,False
776,706,Goodra,Dragon,NaN,90,100,70,110,150,80,6,False
788,712,Bergmite,Ice,NaN,55,69,85,32,35,28,6,False
789,713,Avalugg,Ice,NaN,95,117,184,44,46,28,6,False
792,716,Xerneas,Fairy,NaN,126,131,95,131,98,99,6,True

In [46]:
df['Type 2'] = df['Type 2'].fillna('Unkown')
df.isnull().sum()

#             0
Name          0
Type 1        0
Type 2        0
HP            0
Attack        0
Defense       0
Sp. Atk       0
Sp. Def       0
Speed         0
Generation    0
Legendary     0
dtype: int64